### PR TITLE
Revert "fix: pass on target depends itself (#138)"

### LINKED ISSUE #147: Blocked by transitive dep causing `CircularDependencyException`, while Bazel builds fine
Transitive dependency causing circular dependency error in `4.0.8`

`//external:lib` is not a target that we define in our repo. It's a transitive dependency from GRPC: https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L183-L186

```
[Error] Unexpected error during generation of hashes
com.bazel_diff.hash.RuleHasher$CircularDependencyException: Circular dependency detected:
//external:libuv -> //external:libuv
	at com.bazel_diff.hash.RuleHasher.raiseCircularDependency(RuleHasher.kt:23)
	at com.bazel_diff.hash.RuleHasher.digest(RuleHasher.kt:36)
	at com.bazel_diff.hash.RuleHasher$digest$finalHashValue$1.invoke(RuleHasher.kt:54)
	at com.bazel_diff.hash.RuleHasher$digest$finalHashValue$1.invoke(RuleHasher.kt:41)
	at com.bazel_diff.hash.HashingExtensionsKt.sha256(HashingExtensions.kt:14)
	at com.bazel_diff.hash.RuleHasher.digest(RuleHasher.kt:41)
	at com.bazel_diff.hash.TargetHasher.digest(TargetHasher.kt:38)
	at com.bazel_diff.hash.BuildGraphHasher.hashAllTargets$lambda-6(BuildGraphHasher.kt:107)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

It says in this PR (https://github.com/Tinder/bazel-diff/pull/138) that dependencies depending on themselves would keep Bazel from building, but that's not necessarily the case as this does not interfere with Bazel building.

I don't have the full context on this but if the only reason this exception is being raised is because we're assuming that Bazel wouldn't build, then I think we should change it to a warning message.

### PR DESCRIPTION
**Pull request by tinder-maxwellelliott**
This reverts commit 68e99f10cefa1a0c5b0f355f1e60e1bf3ccc682a.

Fixes #147

### CODE REVIEW

**Comment by arie-stripe** [comment]
Thanks for addressing this so quickly! 🙂

**Comment by tinder-maxwellelliott** [comment]
> Thanks for addressing this so quickly! 🙂 

This worked for you with local testing?

**Comment by arie-stripe** [comment]
@tinder-maxwellelliott yup!
```
❱❱❱ git clone https://github.com/Tinder/bazel-diff.git
Cloning into 'bazel-diff'...
remote: Enumerating objects: 1517, done.
remote: Counting objects: 100% (540/540), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 1517 (delta 297), reused 416 (delta 248), pack-reused 977
Receiving objects: 100% (1517/1517), 571.23 KiB | 2.30 MiB/s, done.
Resolving deltas: 100% (568/568), done.
❱❱❱ cd bazel-diff
❱❱❱ git checkout maxwelle/revert_cyclic_fix
❱❱❱ bazel build //cli:bazel-diff_deploy.jar
❱❱❱ cd ../huge_monorepo
❱❱❱ java -jar ../bazel-diff/bazel-bin/cli/bazel-diff_deploy.jar generate-hashes -b $(which bazel) -w $PWD hashes.json

**Comment by arie-stripe** [comment]
@tinder-maxwellelliott yup!

No warning message though. I'm fine with that, but just in case that's what you expected.
```
❱❱❱ git clone https://github.com/Tinder/bazel-diff.git
Cloning into 'bazel-diff'...
remote: Enumerating objects: 1517, done.
remote: Counting objects: 100% (540/540), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 1517 (delta 297), reused 416 (delta 248), pack-reused 977
Receiving objects: 100% (1517/1517), 571.23 KiB | 2.30 MiB/s, done.
Resolving deltas: 100% (568/568), done.
❱❱❱ cd bazel-diff
❱❱❱ git checkout maxwelle/revert_cyclic_fix
branch 'maxwelle/revert_cyclic_fix' set up to track 'origin/maxwelle/revert_cyclic_fix'.
Switched to a new branch 'maxwelle/revert_cyclic_fix'
❱❱❱ bazel build //cli:bazel-diff_deploy.jar
Starting local Bazel server and connecting to it...
INFO: Analyzed target //cli:bazel-diff_deploy.jar (41 packages loaded, 990 targets configured).
INFO: Found 1 target...
INFO: From KotlinCompile //cli:cli-lib { kt: 31, java: 0, srcjars: 0 } for darwin:
warning: '-Xuse-experimental' is deprecated and will be removed in a future releaseTarget //cli:bazel-diff_deploy.jar up-to-date:
  bazel-bin/cli/bazel-diff_deploy.jar
INFO: Elapsed time: 66.040s, Critical Path: 40.35s
INFO: 49 processes: 12 internal, 31 darwin-sandbox, 6 worker.
INFO: Build completed successfully, 49 total actions
❱❱❱ cd ../huge-monorepo
❱❱❱ java -jar ../bazel-diff/bazel-bin/cli/bazel-diff_deploy.jar generate-hashes -b $(which bazel) -w $PWD hashes.json
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
❱❱❱ echo $?
0
❱❱❱ wc -l hashes.json
<huge_number> hashes.json
```

**Review by arie-stripe — APPROVED** [review]

**Comment by arie-stripe** [comment]
@tinder-maxwellelliott sorry if I'm being a bother, but do you know when this might get merged/released? I can always fork but I'd prefer not to if you plan to cut a release soon 🙂

Thanks again!

**Pull request merged**
