### PR TITLE
Fix computing external repo fine-grained hashes

### PR DESCRIPTION
**Pull request by tgeng**
The previous implementation ignores any change of source files in external repos. That implementation works for maven_install because maven_install does not download any jars into that particular repo. But it does not work for cases when the external repo comes with sources/jars in itself.

We have such use cases internally in Pinterest though I am not aware of any such use cases in common open source world. I have tested this implementation with our internal repo and it seems to work as expected. Interestingly, the difference of introduced in this PR is also sort of captured by the e2e test.

### CODE REVIEW

**Comment by tgeng** [comment]
Hi @tinder-maxwellelliott , can you take a look when you have time? Thanks!

**Comment by tinder-maxwellelliott** [comment]
> Gentle ping 😄 

Thanks again

**Comment by tgeng** [comment]
Could you create another release? Thank you!!

**Comment by tinder-maxwellelliott** [comment]
> Could you create another release? Thank you!!

Done

**Pull request merged**
