### PR TITLE
feat(devex): Initialize Trunk, the universal linter/formatter

### PR DESCRIPTION
**Pull request by nikhilbirmiwal**
Hi! I'm an engineer over at [Trunk.io](https://trunk.io); thanks for building out this awesome tool! We're using it to help power some our products (e.g. our [merge-action repo](https://github.com/trunk-io/merge-action)), as well as our internal CI. 

This PR initializes the Trunk linter/formatter in this repository. It's entirely config as code: the core of this is the `trunk.yaml`, which specifies the linters / formatters to be enabled. Trunk also offers:
- git hooks integration, so all remote branches follow the same uniform set of rules,
- cross-language linting and formatting (invoked by `trunk fmt`),
- tool version management,
- VSCode integration,
- git awareness: trunk will only check incremental diffs to the history of the repo,
- and more!

This PR was generated by [downloading](https://trunk.io/products/check) and running `trunk init` on the repository. If you're curious to learn more, check out [our docs](https://docs.trunk.io/check), or stop by our [Slack](slack.trunk.io).

Throwing this out here to see what you think! Thanks again for creating bazel-diff!

### CODE REVIEW

**Comment by tinder-maxwellelliott** [comment]
I am not sure if hosting this directly in the repo makes sense, can this live in a patch somewhere else and be applied by those who need it?

**Comment by nikhilbirmiwal** [comment]
Hey! Sorry for the late response.

No worries, totally understand if you're not comfortable checking the .trunk/trunk.yaml into your repo - I can just leave my trunk configuration for bazel-diff on my machine (we have a single-player mode that allows this).

Do you want us to merge the other linter configs (for markdownlint, shellcheckrc, yamllint) into bazel-diff? I'm not sure if you'd consider them useful without a corresponding CI step (we do have a GitHub Action that [detects linter issues a PR is introducing (and ignores issues that already exist in the repo)](https://github.com/trunk-io/plugins/pull/424/checks?check_run_id=15730277425), based on linters specified in trunk.yaml, if you'd like for us to show you what that would look like), but I figured I'd ask.

**Comment by tinder-maxwellelliott** [comment]
> Hey! Sorry for the late response.
> 
> No worries, totally understand if you're not comfortable checking the .trunk/trunk.yaml into your repo - I can just leave my trunk configuration for bazel-diff on my machine (we have a single-player mode that allows this).
> 
> Do you want us to merge the other linter configs (for markdownlint, shellcheckrc, yamllint) into bazel-diff? I'm not sure if you'd consider them useful without a corresponding CI step (we do have a GitHub Action that [detects linter issues a PR is introducing (and ignores issues that already exist in the repo)](https://github.com/trunk-io/plugins/pull/424/checks?check_run_id=15730277425), based on linters specified in trunk.yaml, if you'd like for us to show you what that would look like), but I figured I'd ask.

I am not sure how useful those linters are for this project

**Comment by nikhilbirmiwal** [comment]
Totally understood! We'll close this out. Thanks!

**Pull request closed without merging**
